### ISSUE TITLE
Description

### ISSUE THREAD

**Issue by stampFabian** [stampFabian/AutoLogin#29]
short description of our project

**Comment by LsToe** [comment]
**Description**
Our system is designed to automatically log the user into websites with their account details. 
**Functions**
Functions should be:
- Functioning login + hashed password
- Login managed by a database
- Pre-saved websites where you can log in automatically (after entering username and password)
- Multiple accounts per website (by dropdown)
- Websites you can add for yourself
**Target Audience**
Target group are people who can't easily remember passwords/usernames or want to make them more secure. Also, there is an advantage to using our programme, as it is much more efficient due to the auto-login.
